config/routes.rb
Rails.application.routes.draw do
  get 'chapter/index'

  get 'sections/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :chapters do
    resources :sections 

  end
  
  resources :sections do
    resources :lessons
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :sections
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section

  def previous
    return Lesson.find(self.id - 1)
  end

  def next
    return Lesson.find(self.id + 1)
  end
  
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :lessons
  belongs_to :chapter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chapter_controller.rb
class ChapterController < ApplicationController
  def index
    @chapters = Chapter.all
  end

  def show
    @chapter = Chapter.find(params[:id])
  end

  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = Chapter.new(chapter_params)
    if @chapter.save
      redirect_to chapters_path
    else
      render :new
    end
  end

  def edit
    @chapter = Chapter.find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:id])
    if @chapter.update(chapter_params)
      redirect_to chapters_path
    else
      render :edit
    end
  end

  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy
    redirect_to chapters_path
  end

private
  def chapter_params
    params.require(:chapter).permit(:name, :content)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lessons = Lesson.all
  end

  def show
    @lesson = Lesson.find(params[:id])
    @section = Section.find(params[:section_id])
  end

  def new
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new
  end

  def create
    # @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new(lesson_params)
    if @lesson.save
      redirect_to lessons_path
    else
      render :new
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to lessons_path
    else
      render :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to lessons_path
  end

private
  def lesson_params
    params.require(:lesson).permit(:name, :content)
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all
  end

  def show
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:id])
  end

  def new
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.new
  end

  def create
    @chapter = Chapter.find(params[:chapter_id])
    @section = @chapter.sections.new(section_params)
    if @sections.save
      redirect_to sections_path
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_params)
      redirect_to sections_path
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to sections_path
  end

private
  def sections_params
    params.require(:section).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapter_helper.rb
module ChapterHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/chapter/_form.html.erb
<%= render "layouts/errors", :object => @chapter %><%= form_for [@section, @chapter] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/chapter/edit.html.erb
<h1>Edit section</h1>

<%= render "layouts/errors", :object => @section %>

<%= render "form" %>

app/views/chapter/new.html.erb
<h1>Make a new section for <%= @section.name %></h1>

<%= render "form" %>

app/views/chapter/show.html.erb
<h1>Chapter: <%= @chapter.name %>

<h2>Section: <%= @section.name %></h2>

<h3>Lesson: <%= @lesson.name %></h3>

<p><%= @lesson.content %></p>

<p><%= link_to "Edit", edit_section_lesson_path(@chapter, @section, @lesson) %></p>
<p><%= link_to "Delete", chapter_section_lesson_path(@chapter, @section, @lesson),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to sections", sections_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Epiclone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lessons/edit.html.erb
<h1>Edit lesson</h1>

<%= render "layouts/errors", :object => @lesson %>

<%= render "form" %>

app/views/lessons/index.html.erb
<h1>title e.g. rails</h1>

<ul>
  <% @lessons.each do |lesson| %>
    <li><%= link_to lesson.name, lesson_path(lesson) %></li>
  <% end %>
</ul>


<hr>

<%= link_to "New Lesson", new_lesson_path %>

app/views/lessons/new.html.erb
<h1>Make a new lesson for <%= @section.name %></h1>

<%= render "form" %>

app/views/lessons/show.html.erb
<%#<h1>Chapter: <%= @chapter.name %>

<h2>Section: <%= @section.name %></h2>

<h3>Lesson: <%= @lesson.name %></h3>

<p><%= @lesson.content %></p>

<p><%= link_to "Edit", edit_section_lesson_path(@section, @lesson) %></p>
<p><%= link_to "Delete", section_lesson_path(@section, @lesson),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to lessons", lessons_path %></p>

<%= link_to "Previous", section_lesson_path(@lesson.previous()) %>
<%= link_to "Next", section_lesson_path(@lesson.next()) %>

app/views/sections/_form.html.erb
<%= render "layouts/errors", :object => @lesson %><%= form_for [@section, @lesson] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content, size: "24x6" %>
  <br>
  <br>
  <%= f.submit %>
<% end %>

app/views/sections/index.html.erb
<h1>title e.g. rails</h1>

<ul>
  <% @sections.each do |section| %>
    <li><%= link_to section.name, section_path(section) %></li>
  <% end %>
</ul>


<hr>

<%= link_to "New Section", new_section_path %>

app/views/sections/show.html.erb
<%#<h1>Chapter: <%= @chapter.name %>

<h2>Section: <%= @section.name %></h2>

<h3>Lesson: <%= @section.name %></h3>

<p><%= @section.content %></p>

<p><%= link_to "Edit", edit_section_section_path(@section, @section) %></p>
<p><%= link_to "Delete", section_section_path(@section, @section),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to sections", sections_path %></p>

<%= link_to "Previous", section_section_path(@section.previous()) %>
<%= link_to "Next", section_section_path(@section.next()) %>